export const TEAM_LIST_REQUEST = "TEAM_LIST_REQUEST";
export const TEAM_LIST_SUCCESS = "TEAM_LIST_SUCCESS";
export const TEAM_LIST_FAIL = "TEAM_LIST_FAIL";

export const ARTICLES_LIST_REQUEST = "ARTICLES_LIST_REQUEST";
export const ARTICLES_LIST_SUCCESS = "ARTICLES_LIST_SUCCESS";
export const ARTICLES_LIST_FAIL = "ARTICLES_LIST_FAIL";

export const FAQ_LIST_REQUEST = "FAQ_LIST_REQUEST";
export const FAQ_LIST_SUCCESS = "FAQ_LIST_SUCCESS";
export const FAQ_LIST_FAIL = "FAQ_LIST_FAIL";
