# Generated by Django 4.2.5 on 2023-09-23 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_product_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
