# Generated by Django 4.2.5 on 2023-09-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isLiked',
            field=models.BooleanField(default=False),
        ),
    ]
