# Generated by Django 4.2.5 on 2023-09-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_product_isliked'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='oldPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
