# Generated by Django 4.2.5 on 2023-09-30 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0008_product_oldprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('imageURL', models.URLField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('driveURL', models.URLField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
