# Generated by Django 4.2.5 on 2023-10-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_docs_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='classe',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
