# Generated by Django 4.2.5 on 2023-10-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_course_classe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='driveURL',
        ),
        migrations.AddField(
            model_name='course',
            name='docs',
            field=models.FileField(default='', upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
