# Generated by Django 4.2.5 on 2023-10-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_course_driveurl_course_docs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='docs',
        ),
        migrations.AddField(
            model_name='course',
            name='driveURL',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
