# Generated by Django 4.2.5 on 2023-10-08 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_teammember_faq_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='profileImage',
        ),
        migrations.AddField(
            model_name='teammember',
            name='profileImageURL',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
