products = [
    {
        "_id": "1",
        "name": "Airpods Wireless Bluetooth Headphones",
        "description":
        "Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working",
        "brand": "Apple",
        "category": "Electronics",
        "price": 89.99,
        "countInStock": 10,
        "rating": 4.5,
        "numReviews": 12,
        "color": ["#e3f8ff", "#ddde", "red", "blue"],
    },
    {
        "_id": "2",
        "name": "iPhone 11 Pro 256GB Memory",
        "description":
        "Introducing the iPhone 11 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life",
        "brand": "Apple",
        "category": "Electronics",
        "price": 599.99,
        "countInStock": 7,
        "rating": 4.0,
        "numReviews": 8,
        "color": ["#e3f8ff", "#ddde", "#dcfafb", "#ffe8df"],
    },
    {
        "_id": "3",
        "name": "Cannon EOS 80D DSLR Camera",
        "description":
        "Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design",
        "brand": "Cannon",
        "category": "Electronics",
        "price": 929.99,
        "countInStock": 5,
        "rating": 3,
        "numReviews": 12,
        "color": ["#ffe8df"],
    },
    {
        "_id": "4",
        "name": "Sony Playstation 4 Pro White Version",
        "description":
        "The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music",
        "brand": "Sony",
        "category": "Electronics",
        "price": 399.99,
        "countInStock": 11,
        "rating": 5,
        "numReviews": 12,
        "color": ["#dcfafb"],
    },
    {
        "_id": "5",
        "name": "Logitech G-Series Gaming Mouse",
        "description":
        "Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience",
        "brand": "Logitech",
        "category": "Electronics",
        "price": 49.99,
        "countInStock": 7,
        "rating": 3.5,
        "numReviews": 10,
        "color": ["#ffe8df"],
    },
    {
        "_id": "6",
        "name": "Amazon Echo Dot 3rd Generation",
        "description":
        "Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space",
        "brand": "Amazon",
        "category": "Electronics",
        "price": 29.99,
        "countInStock": 0,
        "rating": 4,
        "numReviews": 12,
        "color": ["#e3f8ff"],
    },
    {
        "_id": "7",
        "name": "Smartphone Model X",
        "description":
        "Experience the latest in smartphone technology with the Model X. Packed with features and sleek design.",
        "brand": "TechCorp",
        "category": "Electronics",
        "price": 699.99,
        "countInStock": 25,
        "rating": 4.8,
        "numReviews": 42,
        "color": ["#dcfafb"],
    },
    {
        "_id": "8",
        "name": "Comfy Cushion Chair",
        "description":
        "Sink into relaxation with the plush Comfy Cushion Chair. Perfect for lounging.",
        "brand": "HomeComfort",
        "category": "Furniture",
        "price": 149.99,
        "countInStock": 8,
        "rating": 4.5,
        "numReviews": 20,
        "color": ["#e3f8ff"],
    },
    {
        "_id": "9",
        "name": "Wireless Bluetooth Headphones",
        "description":
        "Immerse yourself in music with these high-quality wireless headphones.",
        "brand": "SoundWave",
        "category": "Electronics",
        "price": 89.99,
        "countInStock": 15,
        "rating": 4.3,
        "numReviews": 28,
        "color": ["#dcfa"],
    },
    {
        "_id": "10",
        "name": "Classic Leather Wallet",
        "description":
        "A timeless accessory, this leather wallet combines style and functionality.",
        "brand": "LeatherCraft",
        "category": "Accessories",
        "price": 39.99,
        "countInStock": 30,
        "rating": 4.7,
        "numReviews": 18,
        "color": ["#dcfa"],
    },
    {
        "_id": "11",
        "name": "Gourmet Coffee Blend",
        "description":
        "Savor the rich flavors of this premium gourmet coffee blend from around the world.",
        "brand": "BeanMasters",
        "category": "Food & Beverages",
        "price": 12.99,
        "countInStock": 50,
        "rating": 4.9,
        "numReviews": 35,
        "color": ["#e3f8ff"],
    },
    {
        "_id": "12",
        "name": "Fitness Tracker Watch",
        "description":
        "Monitor your health and stay active with this advanced fitness tracker watch.",
        "brand": "FitTech",
        "category": "Fitness",
        "price": 79.99,
        "countInStock": 20,
        "rating": 4.6,
        "numReviews": 22,
        "color": ["#dcfafb"],
    },
    {
        "_id": "13",
        "name": "Wireless Bluetooth Headphones",
        "description":
        "Immerse yourself in music with these high-quality wireless headphones.",
        "brand": "SoundWave",
        "category": "Electronics",
        "price": 89.99,
        "countInStock": 15,
        "rating": 4.3,
        "numReviews": 28,
        "color": ["#ffe8df"],
    },
    {
        "_id": "14",
        "name": "Classic Leather Wallet",
        "description":
        "A timeless accessory, this leather wallet combines style and functionality.",
        "brand": "LeatherCraft",
        "category": "Accessories",
        "price": 39.99,
        "countInStock": 30,
        "rating": 4.7,
        "numReviews": 18,
        "color": ["#dcfafb"],
    },
    {
        "_id": "15",
        "name": "Gourmet Coffee Blend",
        "description":
        "Savor the rich flavors of this premium gourmet coffee blend from around the world.",
        "brand": "BeanMasters",
        "category": "Food & Beverages",
        "price": 12.99,
        "countInStock": 50,
        "rating": 4.9,
        "numReviews": 35,
        "color": ["#e3f8ff"],
    },
    {
        "_id": "16",
        "name": "Fitness Tracker Watch",
        "description":
        "Monitor your health and stay active with this advanced fitness tracker watch.",
        "brand": "FitTech",
        "category": "Fitness",
        "price": 79.99,
        "countInStock": 20,
        "rating": 4.6,
        "numReviews": 22,
        "color": ["#ffe8df"],
    },
]
